// <auto-generated/>
/*
 * Copyright 2021 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Adobe.Target.Delivery.Client.OpenAPIDateConverter;

namespace Adobe.Target.Delivery.Model
{
    /// <summary>
    /// Integrations with Audience Manager and Analytics
    /// </summary>
    [DataContract(Name = "ExperienceCloud")]
    public partial class ExperienceCloud : IEquatable<ExperienceCloud>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExperienceCloud" /> class.
        /// </summary>
        /// <param name="audienceManager">audienceManager.</param>
        /// <param name="analytics">analytics.</param>
        public ExperienceCloud(AudienceManager audienceManager = default(AudienceManager), AnalyticsRequest analytics = default(AnalyticsRequest))
        {
            this.AudienceManager = audienceManager;
            this.Analytics = analytics;
        }

        /// <summary>
        /// Gets or Sets AudienceManager
        /// </summary>
        [DataMember(Name = "audienceManager", EmitDefaultValue = false)]
        public AudienceManager AudienceManager { get; set; }

        /// <summary>
        /// Gets or Sets Analytics
        /// </summary>
        [DataMember(Name = "analytics", EmitDefaultValue = false)]
        public AnalyticsRequest Analytics { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExperienceCloud {\n");
            sb.Append("  AudienceManager: ").Append(AudienceManager).Append("\n");
            sb.Append("  Analytics: ").Append(Analytics).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExperienceCloud);
        }

        /// <summary>
        /// Returns true if ExperienceCloud instances are equal
        /// </summary>
        /// <param name="input">Instance of ExperienceCloud to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExperienceCloud input)
        {
            if (input == null)
                return false;

            return
                (
                    this.AudienceManager == input.AudienceManager ||
                    (this.AudienceManager != null &&
                    this.AudienceManager.Equals(input.AudienceManager))
                ) &&
                (
                    this.Analytics == input.Analytics ||
                    (this.Analytics != null &&
                    this.Analytics.Equals(input.Analytics))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AudienceManager != null)
                    hashCode = hashCode * 59 + this.AudienceManager.GetHashCode();
                if (this.Analytics != null)
                    hashCode = hashCode * 59 + this.Analytics.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
